version: "3"

services:

  # TODO: Verficiar se o port é 3002 ou 3000 no lado do react
  pong_frontend:
    container_name: pong-frontend
    build: pong_frontend/
    ports:
      - '3002:3000'
    build: pong_frontend/
    environment:
      - NODE_ENV=production
    networks:
      pong_network:
        ipv4_address: 10.5.0.4
    restart: always
    depends_on:
      - pong_backend
    volumes:
      - ./pong_frontend:/usr/src/app/
    env_file:
      - .env


  pong_backend:
    container_name: pong-backend
    build: pong_backend/
    ports:
      - '3021:3021'
    networks:
      pong_network:
        ipv4_address: 10.5.0.6
    restart: always
    environment:
      - NODE_ENV=production
    depends_on:
      - pong_database
    volumes:
      - ./pong_backend:/usr/src/app/
    env_file:
      - .env


  pong_database:
    image: postgres:latest
    container_name: pong-database
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pong_game
    ports:
      - '5432:5432'
    networks:
      pong_network:
        ipv4_address: 10.5.0.2 
    restart: always


  adminer:
    image: adminer
    depends_on:
      - pong_database 
    networks:
     - pong_network
    container_name: pong-adminer
    environment:
      - ADMINER_DEFAULT_SERVER=database
    ports:
      - "8080:8080"

      

networks:
  pong_network:
    driver: 'bridge'
    ipam:
      config:
        - subnet: 10.5.0.0/24

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      device: ./postgres_data/
      o: bind
